package org.smsm.papercontrol;
import android.app.PendingIntent;
import android.appwidget.*;
import android.content.*;
import android.graphics.Color;
import android.os.*;
import android.widget.RemoteViews;
import java.util.*;
public class PaperWidget extends AppWidgetProvider {
 static Intent action(Context c,String action){return new Intent(c,WidgetActionActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_MULTIPLE_TASK|Intent.FLAG_ACTIVITY_NO_ANIMATION).putExtra("action",action);}
 static boolean meetings(Context c,int id){return VaultStore.prefs(c).getString("tab_"+id,"tasks").equals("meetings");}
 static boolean portrait(Context c){return c.getResources().getConfiguration().orientation!=android.content.res.Configuration.ORIENTATION_LANDSCAPE;}
 static boolean compact(Context c,int id){return AppWidgetManager.getInstance(c).getAppWidgetOptions(id).getInt(portrait(c)?AppWidgetManager.OPTION_APPWIDGET_MAX_HEIGHT:AppWidgetManager.OPTION_APPWIDGET_MIN_HEIGHT,160)<260;}
 static int layout(Context c,int id){boolean large=c.getResources().getConfiguration().fontScale>1.15f;return compact(c,id)?(large?R.layout.paper_widget_compact_large_font:R.layout.paper_widget_compact):(large?R.layout.paper_widget_large_font:R.layout.paper_widget);}
 static int buttonWidth(Context c,int id){return Math.max(42,(AppWidgetManager.getInstance(c).getAppWidgetOptions(id).getInt(portrait(c)?AppWidgetManager.OPTION_APPWIDGET_MIN_WIDTH:AppWidgetManager.OPTION_APPWIDGET_MAX_WIDTH,300)-34)/4);}
 private static PendingIntent click(Context c,int id,String name){Intent i=action(c,name).setData(android.net.Uri.parse("papercontrol://widget/"+id+"/"+name)).putExtra("widget",id);if(name.equals("add"))i.setClass(c,TaskEditorActivity.class);if(name.equals("refresh")||name.startsWith("tab-")){i.setClass(c,TaskActionReceiver.class);return PendingIntent.getBroadcast(c,id,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);}return PendingIntent.getActivity(c,id,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);}
 public static RemoteViews row(Context c,TaskDocument.Task t,boolean compact){RemoteViews r=rowBase(c,t.title,t.done,compact);r.setContentDescription(R.id.task_toggle,(t.done?"미완료로 변경: ":"완료: ")+t.title);r.setContentDescription(R.id.task_title,"수정: "+t.title);for(String a:new String[]{"toggle","edit"})r.setOnClickFillInIntent(a.equals("toggle")?R.id.task_toggle:R.id.task_title,new Intent().putExtra("action",a).putExtra("key",t.key).putExtra("raw",t.raw));return r;}
 public static RemoteViews meetingRow(Context c,MeetingDocument d,boolean compact){RemoteViews r=rowBase(c,d.when()+"  ·  "+d.title,d.done,compact);r.setContentDescription(R.id.task_toggle,(d.done?"회의 미완료로 변경: ":"회의 완료: ")+d.title);r.setContentDescription(R.id.task_title,d.when()+" "+d.title+", 회의 노트 열기");r.setOnClickFillInIntent(R.id.task_toggle,new Intent().putExtra("action","meeting-toggle").putExtra("key",d.path).putExtra("raw",TaskDocument.hash(d.raw)));r.setOnClickFillInIntent(R.id.task_title,new Intent().putExtra("action","meeting-open").putExtra("key",d.path));return r;}
 private static RemoteViews rowBase(Context c,String title,boolean done,boolean compact){RemoteViews r=new RemoteViews(c.getPackageName(),compact?R.layout.task_row_compact:R.layout.task_row);r.setTextViewText(R.id.task_title,title);r.setTextColor(R.id.task_title,Color.parseColor(done?"#5D6D63":"#20372D"));r.setInt(R.id.task_title,"setPaintFlags",done?17:1);r.setImageViewResource(R.id.task_toggle,done?R.drawable.check_done:R.drawable.check_empty);return r;}
 public static void refresh(Context c){new Thread(()->updateAll(c.getApplicationContext()),"widget-refresh").start();}
 public static synchronized void updateAll(Context c){if(WidgetFeedback.isBusy())return;AppWidgetManager m=AppWidgetManager.getInstance(c);for(int id:m.getAppWidgetIds(new ComponentName(c,PaperWidget.class)))update(c,m,id);}
 static void update(Context c,AppWidgetManager m,int id){VaultStore store=new VaultStore(c);boolean meeting=meetings(c,id),compact=compact(c,id);List<TaskDocument.Task> tasks=new ArrayList<>();List<MeetingDocument> meetings=new ArrayList<>();String error="";try{if(meeting)meetings=store.meetings();else tasks=new TaskDocument(store.read(store.source())).today(VaultStore.day());}catch(Exception e){error=e instanceof SecurityException?"Vault 권한을 다시 연결해 주세요":e.getMessage();if(error==null)error="목록을 읽지 못했습니다.";}
  int total=meeting?meetings.size():tasks.size();long done=meeting?meetings.stream().filter(d->d.done).count():tasks.stream().filter(t->t.done).count();float ratio=total==0?0:done/(float)total;
  RemoteViews v=new RemoteViews(c.getPackageName(),layout(c,id));v.setTextViewText(R.id.widget_count,done+" / "+total);v.setContentDescription(R.id.widget_count,(meeting?"회의":"할 일")+" "+total+"개 중 "+done+"개 완료, 눌러 새로고침");v.setTextViewText(R.id.task_empty,error.isEmpty()?(meeting?"다가오는 회의가 없습니다":"오늘 할 일을 추가해 보세요"):error);v.setEmptyView(R.id.task_list,R.id.task_empty);
  v.setInt(R.id.tab_tasks,"setBackgroundResource",meeting?R.drawable.tab_inactive:R.drawable.tab_active);v.setInt(R.id.tab_meetings,"setBackgroundResource",meeting?R.drawable.tab_active:R.drawable.tab_inactive);v.setContentDescription(R.id.tab_tasks,meeting?"할 일 탭":"할 일 탭, 선택됨");v.setContentDescription(R.id.tab_meetings,meeting?"회의 탭, 선택됨":"회의 탭");
  v.setImageViewBitmap(R.id.progress_wave,WidgetGraphics.wave(ratio,-1));v.setViewVisibility(R.id.wave_overlay,android.view.View.GONE);
  android.graphics.Paint countPaint=new android.graphics.Paint(3);countPaint.setTypeface(android.graphics.Typeface.create("sans-serif",android.graphics.Typeface.BOLD));countPaint.setTextSize(20*c.getResources().getConfiguration().fontScale);int widgetWidth=m.getAppWidgetOptions(id).getInt(portrait(c)?AppWidgetManager.OPTION_APPWIDGET_MIN_WIDTH:AppWidgetManager.OPTION_APPWIDGET_MAX_WIDTH,300);float track=Math.max(0,widgetWidth-16-112-32-16-4-countPaint.measureText(done+" / "+total));

  String git=store.gitState();v.setImageViewBitmap(R.id.git_dot,WidgetGraphics.dot(git));v.setContentDescription(R.id.git_dot,"Git "+(git.equals("verified")?"최근 연결 확인":git.equals("pending")?"요청 중":git.equals("error")?"연결 오류":"확인되지 않음")+", 자세히 보기");
  Intent template=new Intent(c,TaskActionReceiver.class).setData(android.net.Uri.parse("papercontrol://widget/"+id+"/rows-030")).putExtra("widget",id);int mutable=Build.VERSION.SDK_INT>=31?PendingIntent.FLAG_MUTABLE:0;v.setPendingIntentTemplate(R.id.task_list,PendingIntent.getBroadcast(c,id,template,PendingIntent.FLAG_UPDATE_CURRENT|mutable));
  if(Build.VERSION.SDK_INT>=31){RemoteViews.RemoteCollectionItems.Builder b=new RemoteViews.RemoteCollectionItems.Builder().setHasStableIds(true).setViewTypeCount(1);Set<Long> keys=new HashSet<>();if(meeting){for(MeetingDocument d:meetings){long key=key(d.path,keys);b.addItem(key,meetingRow(c,d,compact));}}else for(TaskDocument.Task t:tasks)b.addItem(key(t.key,keys),row(c,t,compact));v.setRemoteAdapter(R.id.task_list,b.build());}
  else{Intent service=new Intent(c,TasksService.class).putExtra(AppWidgetManager.EXTRA_APPWIDGET_ID,id);service.setData(android.net.Uri.parse("papercontrol://tasks/"+id+"/"+meeting+"/"+compact));v.setRemoteAdapter(R.id.task_list,service);}
  WidgetFeedback.paint(c,v,id);int[] ids={R.id.tab_tasks,R.id.tab_meetings,R.id.widget_count,R.id.git_dot,R.id.task_empty,R.id.add_task,R.id.open_meeting,R.id.start_analysis,R.id.git_sync};String[] actions={"tab-tasks","tab-meetings","refresh","connection","settings","add","open","analyze","sync"};for(int n=0;n<ids.length;n++)v.setOnClickPendingIntent(ids[n],click(c,id,actions[n]));m.updateAppWidget(id,v);WidgetFeedback.wave(c,id,ratio,track);if(Build.VERSION.SDK_INT<31)m.notifyAppWidgetViewDataChanged(id,R.id.task_list);
 }
 private static long key(String value,Set<Long> keys){long k=Long.parseUnsignedLong(TaskDocument.hash(value).substring(0,16),16);while(!keys.add(k))k++;return k;}
 @Override public void onUpdate(Context c,AppWidgetManager m,int[] ids){refresh(c);}
 @Override public void onAppWidgetOptionsChanged(Context c,AppWidgetManager m,int id,Bundle options){refresh(c);}
 @Override public void onDeleted(Context c,int[] ids){for(int id:ids)VaultStore.prefs(c).edit().remove("tab_"+id).apply();}
 @Override public void onReceive(Context c,Intent i){super.onReceive(c,i);if(Arrays.asList(AppWidgetManager.ACTION_APPWIDGET_UPDATE,AppWidgetManager.ACTION_APPWIDGET_OPTIONS_CHANGED,Intent.ACTION_DATE_CHANGED,Intent.ACTION_TIME_CHANGED,Intent.ACTION_TIMEZONE_CHANGED).contains(i.getAction())){PendingResult p=goAsync();new Thread(()->{try{updateAll(c.getApplicationContext());}finally{p.finish();}},"widget-broadcast").start();}}
}
